//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEC_OLIGO
    {
        public int SPEC_OLIGO_ID { get; set; }
        public System.DateTime CREATE_DTM { get; set; }
        public int SPEC_STATE_ID { get; set; }
        public int OLIGO_TYPE { get; set; }
        public int WORKFLOW_PATH_ID { get; set; }
        public int BRANCH_LOCATION_ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<int> REF_ID { get; set; }
        public Nullable<int> SCALE_ID { get; set; }
        public int SPEC_DELIVERY_ID { get; set; }
        public int SPEC_ORDER_ID { get; set; }
        public double GUAR_MIN_SHIP_VAL { get; set; }
        public int GUAR_MIN_SHIP_UOM_ID { get; set; }
        public double GUAR_MIN_SYNTH_VAL { get; set; }
        public int GUAR_MIN_SYNTH_UOM_ID { get; set; }
        public double GUAR_MAX_SYNTH_VAL { get; set; }
        public int GUAR_MAX_SYNTH_UOM_ID { get; set; }
        public Nullable<double> PURITY_GUAR_PCT { get; set; }
        public int PURITY_EXPL_ID { get; set; }
        public bool PURITY_GUAR_USABLE { get; set; }
        public Nullable<int> YIELD_EXPL_ID { get; set; }
        public int PROCESS_PRIORITY { get; set; }
        public Nullable<int> PURIFICATION_ID { get; set; }
        public Nullable<int> PARENT_SPEC_OLIGO_ID { get; set; }
        public int VERSION_NBR { get; set; }
        public System.DateTime VERSION_DTM { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SEQUENCE { get; set; }
        public string SEQUENCE_DESCRIPTION { get; set; }
        public string SEQUENCE_CODON { get; set; }
        public string EXTERNAL_REF_ID { get; set; }
        public Nullable<int> DIRECTED_TYPE { get; set; }
        public Nullable<bool> IS_SYNTHESIS_REQUIRED { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual SPEC_DELIVERY SPEC_DELIVERY { get; set; }
    }
}
